// How to render map with locations
// https://apidocs.geoapify.com/samples/geojson/geojson-points-layer-mapbox/

// User GeoLocation request Data
// Request HTTP                             Api Key
// https://api.geoapify.com/v1/ipinfo?&apiKey=b5af20f3a98f4f1d8ce5eec60ff98ce3

let locationResponse = {
  city: {
    names: {
      en: "Brisbane",
    },
    name: "Brisbane",
  },
  continent: {
    code: "OC",
    geoname_id: 6255151,
    names: {
      de: "Ozeanien",
      en: "Oceania",
      es: "Oceanía",
      fa: "اقیانوسیه",
      fr: "Océanie",
      ja: "オセアニア",
      ko: "오세아니아",
      "pt-BR": "Oceania",
      ru: "Океания",
      "zh-CN": "大洋洲",
    },
    name: "Oceania",
  },
  country: {
    geoname_id: 2077456,
    iso_code: "AU",
    names: {
      de: "Australien",
      en: "Australia",
      es: "Australia",
      fa: "استرالیا",
      fr: "Australie",
      ja: "オーストラリア",
      ko: "오스트레일리아",
      "pt-BR": "Austrália",
      ru: "Австралия",
      "zh-CN": "澳大利亚",
    },
    name: "Australia",
    name_native: "Australia",
    phone_code: "61",
    capital: "Canberra",
    currency: "AUD",
    flag: "🇦🇺",
    languages: [
      {
        iso_code: "en",
        name: "English",
        name_native: "English",
      },
    ],
  },
  location: {
    latitude: -27.4669,
    longitude: 153.0397,
  },
  subdivisions: [
    {
      names: {
        en: "Queensland",
      },
    },
  ],
  state: {
    name: "Queensland",
  },
  datasource: [
    {
      name: "IP to City Lite",
      attribution: "<a href='https://db-ip.com'>IP Geolocation by DB-IP</a>",
      license: "Creative Commons Attribution License",
    },
  ],
  ip: "203.30.3.200",
};

// Dining Venue Finder
// Request HTTP                                                             Longitude           Latitude        diameter              Longitude             Latitude        Amount of results       Api Key
// https://api.geoapify.com/v2/places?categories=catering&filter=circle:153.03256417709395,-27.523417252872235,5000&bias=proximity:153.03256417709395,-27.523417252872235&limit=20&apiKey=b5af20f3a98f4f1d8ce5eec60ff98ce3

let diningResponse = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {
        name: "BillyKart Kitchen",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        street: "Mametz Street",
        lon: 153.028983,
        lat: -27.5235926,
        state_code: "QLD",
        formatted:
          "BillyKart Kitchen, Mametz Street, Greater Brisbane QLD 4103, Australia",
        address_line1: "BillyKart Kitchen",
        address_line2: "Mametz Street, Greater Brisbane QLD 4103, Australia",
        categories: ["catering", "catering.cafe"],
        details: ["details"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "BillyKart Kitchen",
            osm_id: 4582058396,
            amenity: "cafe",
            "name:en": "BillyKart Kitchen",
            website: "https://billykart.com.au/",
            osm_type: "n",
          },
        },
        website: "https://billykart.com.au/",
        name_international: {
          en: "BillyKart Kitchen",
        },
        distance: 354,
        place_id:
          "517ba4c16ded206340591918232a0a863bc0f00103f9019ca91c110100000092031142696c6c794b617274204b69746368656e",
      },
      geometry: {
        type: "Point",
        coordinates: [153.028983, -27.523592599456695],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Café Ô-Mai",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Franklin Street",
        lon: 153.0299682,
        lat: -27.5186094,
        state_code: "QLD",
        formatted: "Café Ô-Mai, Franklin Street, Annerley QLD 4103, Australia",
        address_line1: "Café Ô-Mai",
        address_line2: "Franklin Street, Annerley QLD 4103, Australia",
        categories: ["catering", "catering.cafe"],
        details: ["details.catering", "details.facilities"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Café Ô-Mai",
            osm_id: 456713166,
            amenity: "cafe",
            cuisine: "vietnamese",
            osm_type: "n",
            outdoor_seating: "yes",
          },
        },
        facilities: {
          outdoor_seating: true,
        },
        catering: {
          cuisine: "vietnamese",
        },
        distance: 591,
        place_id:
          "5170ddde7ff5206340591f11ea95c3843bc0f00103f901cee3381b0000000092030c436166c3a920c3942d4d6169",
      },
      geometry: {
        type: "Point",
        coordinates: [153.02996819999998, -27.5186093994572],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Bahn Mi",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Cracknell Road",
        lon: 153.0299017,
        lat: -27.518566,
        state_code: "QLD",
        formatted: "Bahn Mi, Cracknell Road, Annerley QLD 4103, Australia",
        address_line1: "Bahn Mi",
        address_line2: "Cracknell Road, Annerley QLD 4103, Australia",
        categories: ["catering", "catering.fast_food"],
        details: ["details.catering"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Bahn Mi",
            osm_id: 456713167,
            amenity: "fast_food",
            cuisine: "vietnamese",
            osm_type: "n",
          },
        },
        catering: {
          cuisine: "vietnamese",
        },
        distance: 598,
        place_id:
          "5109f368f4f4206340597e7cc8bdc0843bc0f00103f901cfe3381b000000009203074261686e204d69",
      },
      geometry: {
        type: "Point",
        coordinates: [153.0299017, -27.518565999457216],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Pho Queue",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Cracknell Road",
        lon: 153.0298476,
        lat: -27.5185443,
        state_code: "QLD",
        formatted: "Pho Queue, Cracknell Road, Annerley QLD 4103, Australia",
        address_line1: "Pho Queue",
        address_line2: "Cracknell Road, Annerley QLD 4103, Australia",
        categories: [
          "catering",
          "catering.restaurant",
          "catering.restaurant.vietnamese",
        ],
        details: ["details.catering"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Pho Queue",
            osm_id: 9194853110,
            amenity: "restaurant",
            cuisine: "vietnamese",
            osm_type: "n",
          },
        },
        catering: {
          cuisine: "vietnamese",
        },
        distance: 603,
        place_id:
          "51a73bf482f42063405927b2b751bf843bc0f00103f901f6520e240200000092030950686f205175657565",
      },
      geometry: {
        type: "Point",
        coordinates: [153.0298476, -27.5185442994572],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "A Mano Café",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Cracknell Road",
        lon: 153.0297546,
        lat: -27.5185113,
        state_code: "QLD",
        formatted: "A Mano Café, Cracknell Road, Annerley QLD 4103, Australia",
        address_line1: "A Mano Café",
        address_line2: "Cracknell Road, Annerley QLD 4103, Australia",
        categories: [
          "catering",
          "catering.cafe",
          "catering.cafe.coffee",
          "catering.cafe.coffee_shop",
        ],
        details: ["details.catering", "details.facilities"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "A Mano Café",
            osm_id: 456713171,
            amenity: "cafe",
            cuisine: "coffee_shop",
            osm_type: "n",
            outdoor_seating: "yes",
          },
        },
        facilities: {
          outdoor_seating: true,
        },
        catering: {
          cuisine: "coffee_shop",
        },
        distance: 610,
        place_id:
          "51fb3cebbff32063405975c61128bd843bc0f00103f901d3e3381b0000000092030c41204d616e6f20436166c3a9",
      },
      geometry: {
        type: "Point",
        coordinates: [153.02975460000002, -27.51851129945722],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Red Lotus",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Cracknell Road",
        lon: 153.0297081,
        lat: -27.5184904,
        state_code: "QLD",
        formatted: "Red Lotus, Cracknell Road, Annerley QLD 4103, Australia",
        address_line1: "Red Lotus",
        address_line2: "Cracknell Road, Annerley QLD 4103, Australia",
        categories: [
          "catering",
          "catering.restaurant",
          "catering.restaurant.vietnamese",
        ],
        details: ["details.catering", "details.facilities"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Red Lotus",
            osm_id: 456713172,
            amenity: "restaurant",
            cuisine: "vietnamese",
            smoking: "no",
            osm_type: "n",
            takeaway: "yes",
            outdoor_seating: "yes",
          },
        },
        facilities: {
          smoking: false,
          outdoor_seating: true,
          takeaway: true,
        },
        catering: {
          cuisine: "vietnamese",
        },
        distance: 615,
        place_id:
          "51a4bd665ef3206340596ef56cc9bb843bc0f00103f901d4e3381b00000000920309526564204c6f747573",
      },
      geometry: {
        type: "Point",
        coordinates: [153.0297081, -27.518490399457214],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Chardons Corner Hotel",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Ipswich Road",
        housenumber: "688",
        lon: 153.0294407,
        lat: -27.5185813,
        state_code: "QLD",
        formatted:
          "Chardons Corner Hotel, 688 Ipswich Road, Annerley QLD 4103, Australia",
        address_line1: "Chardons Corner Hotel",
        address_line2: "688 Ipswich Road, Annerley QLD 4103, Australia",
        categories: ["catering", "catering.pub"],
        details: ["details"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Chardons Corner Hotel",
            osm_id: 429164909,
            amenity: "pub",
            website: "https://www.chardonshotel.com.au",
            operator: "ALH Group",
            osm_type: "n",
            "addr:state": "QLD",
            check_date: "2023-12-23",
            "addr:street": "Ipswich Road",
            "addr:suburb": "Annerley",
            "addr:postcode": 4103,
            "addr:housenumber": 688,
          },
        },
        website: "https://www.chardonshotel.com.au",
        operator: "ALH Group",
        distance: 618,
        place_id:
          "517b759f2df120634059667c79bec1843bc0f00103f9016d8994190000000092031543686172646f6e7320436f726e657220486f74656c",
      },
      geometry: {
        type: "Point",
        coordinates: [153.02944069999998, -27.518581299457217],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Lucky Cat Cafe",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Villa Street",
        lon: 153.0291171,
        lat: -27.5181401,
        state_code: "QLD",
        formatted: "Lucky Cat Cafe, Villa Street, Annerley QLD 4103, Australia",
        address_line1: "Lucky Cat Cafe",
        address_line2: "Villa Street, Annerley QLD 4103, Australia",
        categories: ["catering", "catering.cafe"],
        details: ["details"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Lucky Cat Cafe",
            theme: "cat",
            osm_id: 6212314486,
            amenity: "cafe",
            website: "https://www.luckycatcafe.com/",
            osm_type: "n",
          },
        },
        website: "https://www.luckycatcafe.com/",
        distance: 677,
        place_id:
          "512308fc86ee2063405945ea5dd4a4843bc0f00103f901766548720100000092030e4c75636b79204361742043616665",
      },
      geometry: {
        type: "Point",
        coordinates: [153.02911709999998, -27.51814009945726],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Pizza Capers",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Devon Street",
        lon: 153.0298467,
        lat: -27.5177732,
        state_code: "QLD",
        formatted: "Pizza Capers, Devon Street, Annerley QLD 4103, Australia",
        address_line1: "Pizza Capers",
        address_line2: "Devon Street, Annerley QLD 4103, Australia",
        categories: [
          "catering",
          "catering.fast_food",
          "catering.fast_food.pizza",
        ],
        details: ["details.catering"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Pizza Capers",
            osm_id: 444701918,
            amenity: "fast_food",
            cuisine: "pizza",
            osm_type: "n",
          },
        },
        catering: {
          cuisine: "pizza",
        },
        distance: 681,
        place_id:
          "51980c1181f420634059186acec88c843bc0f00103f901de9c811a0000000092030c50697a7a6120436170657273",
      },
      geometry: {
        type: "Point",
        coordinates: [153.0298467, -27.51777319945731],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Virk Cafe",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Ipswich Road",
        lon: 153.0294985,
        lat: -27.517554,
        state_code: "QLD",
        formatted: "Virk Cafe, Ipswich Road, Annerley QLD 4103, Australia",
        address_line1: "Virk Cafe",
        address_line2: "Ipswich Road, Annerley QLD 4103, Australia",
        categories: ["catering", "catering.cafe"],
        details: [],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Virk Cafe",
            osm_id: 9202459595,
            amenity: "cafe",
            osm_type: "n",
          },
        },
        distance: 717,
        place_id:
          "51fe98d6a6f1206340594a953d6b7e843bc0f00103f901cb638224020000009203095669726b2043616665",
      },
      geometry: {
        type: "Point",
        coordinates: [153.0294985, -27.517553999457313],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Red Rooster",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4105",
        city_district: "Moorooka",
        district: "Greater Brisbane",
        neighbourhood: "Clifton Hill",
        suburb: "Moorooka",
        street: "Longueval Street",
        lon: 153.02468054495966,
        lat: -27.523912,
        state_code: "QLD",
        formatted:
          "Red Rooster, Longueval Street, Moorooka QLD 4105, Australia",
        address_line1: "Red Rooster",
        address_line2: "Longueval Street, Moorooka QLD 4105, Australia",
        categories: [
          "building",
          "building.catering",
          "catering",
          "catering.fast_food",
        ],
        details: ["details", "details.catering", "details.facilities"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Red Rooster",
            brand: "Red Rooster",
            osm_id: 51366719,
            amenity: "fast_food",
            cuisine: "chicken",
            building: "yes",
            osm_type: "w",
            takeaway: "yes",
            drive_through: "no",
            "brand:wikidata": "Q376466",
          },
        },
        brand: "Red Rooster",
        brand_details: {
          wikidata: "Q376466",
        },
        facilities: {
          takeaway: true,
        },
        catering: {
          cuisine: "chicken",
        },
        distance: 770,
        place_id:
          "5160aeda2eca20634059fda5c7181f863bc0f00102f9013fcb0f030000000092030b52656420526f6f73746572",
      },
      geometry: {
        type: "Point",
        coordinates: [153.02468054495966, -27.523911999456676],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Bruno's BNE",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4121",
        city_district: "Tarragindi",
        district: "Greater Brisbane",
        suburb: "Tarragindi",
        street: "Laura Street",
        lon: 153.040706,
        lat: -27.5199657,
        state_code: "QLD",
        formatted: "Bruno's BNE, Laura Street, Tarragindi QLD 4121, Australia",
        address_line1: "Bruno's BNE",
        address_line2: "Laura Street, Tarragindi QLD 4121, Australia",
        categories: ["catering", "catering.cafe"],
        details: [],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Bruno's BNE",
            osm_id: 439983290,
            amenity: "cafe",
            osm_type: "n",
          },
        },
        distance: 891,
        place_id:
          "510958ab764d21634059b835da781c853bc0f00103f901ba9c391a0000000092030b4272756e6f277320424e45",
      },
      geometry: {
        type: "Point",
        coordinates: [153.04070600000003, -27.51996569945706],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "KFC",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Chester Road",
        lon: 153.0309415668155,
        lat: -27.51513875,
        state_code: "QLD",
        formatted: "KFC, Chester Road, Annerley QLD 4103, Australia",
        address_line1: "KFC",
        address_line2: "Chester Road, Annerley QLD 4103, Australia",
        categories: [
          "building",
          "building.catering",
          "catering",
          "catering.fast_food",
        ],
        details: ["details", "details.catering", "details.facilities"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "KFC",
            brand: "KFC",
            osm_id: 37965186,
            amenity: "fast_food",
            cuisine: "chicken",
            alt_name: "Kentucky Fried Chicken",
            building: "yes",
            osm_type: "w",
            takeaway: "yes",
            "brand:wikidata": "Q524757",
            "brand:wikipedia": "en:KFC",
          },
        },
        brand: "KFC",
        brand_details: {
          wikidata: "Q524757",
          wikipedia: "en:KFC",
        },
        name_other: {
          alt_name: "Kentucky Fried Chicken",
        },
        facilities: {
          takeaway: true,
        },
        catering: {
          cuisine: "chicken",
        },
        distance: 922,
        place_id:
          "51e7312b79fd2063405991d21122e0833bc0f00102f901824d4302000000009203034b4643",
      },
      geometry: {
        type: "Point",
        coordinates: [153.03094156681547, -27.515138749457552],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Taco Bell",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Ipswich Road",
        housenumber: "594",
        lon: 153.03098551620428,
        lat: -27.5147307,
        state_code: "QLD",
        formatted: "Taco Bell, 594 Ipswich Road, Annerley QLD 4103, Australia",
        address_line1: "Taco Bell",
        address_line2: "594 Ipswich Road, Annerley QLD 4103, Australia",
        categories: [
          "building",
          "building.catering",
          "catering",
          "catering.fast_food",
        ],
        details: ["details", "details.catering", "details.facilities"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Taco Bell",
            brand: "Taco Bell",
            osm_id: 37965187,
            amenity: "fast_food",
            cuisine: "tex-mex",
            building: "yes",
            osm_type: "w",
            takeaway: "yes",
            "addr:street": "Ipswich Road",
            "addr:postcode": 4103,
            "addr:province": "Queensland",
            drive_through: "yes",
            opening_hours: "09:00-22:00",
            "brand:wikidata": "Q752941",
            "brand:wikipedia": "en:Taco Bell",
            "addr:housenumber": 594,
          },
        },
        opening_hours: "09:00-22:00",
        brand: "Taco Bell",
        brand_details: {
          wikidata: "Q752941",
          wikipedia: "en:Taco Bell",
        },
        facilities: {
          takeaway: true,
        },
        catering: {
          cuisine: "tex-mex",
        },
        distance: 964,
        place_id:
          "51e75756d5fd20634059e66a2064c5833bc0f00102f901834d4302000000009203095461636f2042656c6c",
      },
      geometry: {
        type: "Point",
        coordinates: [153.03098551620425, -27.514730699457594],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Bean on the Green",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4105",
        city_district: "Moorooka",
        district: "Greater Brisbane",
        neighbourhood: "Moorvale",
        suburb: "Moorooka",
        street: "Koala Road",
        housenumber: "76",
        lon: 153.0281133,
        lat: -27.5312026,
        state_code: "QLD",
        formatted:
          "Bean on the Green, 76 Koala Road, Moorooka QLD 4105, Australia",
        address_line1: "Bean on the Green",
        address_line2: "76 Koala Road, Moorooka QLD 4105, Australia",
        categories: ["catering", "catering.cafe"],
        details: ["details"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Bean on the Green",
            osm_id: 9871158330,
            amenity: "cafe",
            website: "https://www.theclubhousemoorooka.org/",
            osm_type: "n",
            opening_hours: "Mo-Su 06:30-13:00",
          },
        },
        website: "https://www.theclubhousemoorooka.org/",
        opening_hours: "Mo-Su 06:30-13:00",
        distance: 968,
        place_id:
          "51a502dd4de620634059a636c0e4fc873bc0f00103f9013aec5d4c020000009203114265616e206f6e2074686520477265656e",
      },
      geometry: {
        type: "Point",
        coordinates: [153.0281133, -27.531202599455945],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "T&L Carvery Cafe",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Bower Street",
        lon: 153.0348290484298,
        lat: -27.514333649999998,
        state_code: "QLD",
        formatted:
          "T&L Carvery Cafe, Bower Street, Annerley QLD 4103, Australia",
        address_line1: "T&L Carvery Cafe",
        address_line2: "Bower Street, Annerley QLD 4103, Australia",
        categories: [
          "building",
          "building.catering",
          "catering",
          "catering.cafe",
        ],
        details: [],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "T&L Carvery Cafe",
            osm_id: 643029627,
            amenity: "cafe",
            building: "yes",
            osm_type: "w",
          },
        },
        distance: 1024,
        place_id:
          "519efece511d2163405924a7bb5eab833bc0f00102f9017bda53260000000092031054264c20436172766572792043616665",
      },
      geometry: {
        type: "Point",
        coordinates: [153.0348290484298, -27.51433364945764],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "The Pink Salmon",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4121",
        city_district: "Tarragindi",
        district: "Greater Brisbane",
        suburb: "Tarragindi",
        street: "Ekibin Road East",
        lon: 153.0389472,
        lat: -27.5155512,
        state_code: "QLD",
        formatted:
          "The Pink Salmon, Ekibin Road East, Tarragindi QLD 4121, Australia",
        address_line1: "The Pink Salmon",
        address_line2: "Ekibin Road East, Tarragindi QLD 4121, Australia",
        categories: [
          "catering",
          "catering.restaurant",
          "catering.restaurant.seafood",
        ],
        details: [
          "details",
          "details.catering",
          "details.contact",
          "details.facilities",
        ],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "The Pink Salmon",
            phone: "+61 7 3892 2522",
            osm_id: 437981620,
            amenity: "restaurant",
            cuisine: "seafood",
            smoking: "no",
            delivery: "no",
            osm_type: "n",
            takeaway: "yes",
            opening_hours: "Tu-Su,PH 09:00-20:00",
          },
        },
        opening_hours: "Tu-Su,PH 09:00-20:00",
        contact: {
          phone: "+61 7 3892 2522",
        },
        facilities: {
          smoking: false,
          takeaway: true,
          delivery: false,
        },
        catering: {
          cuisine: "seafood",
        },
        distance: 1076,
        place_id:
          "51a9c8320e3f216340596b15d529fb833bc0f00103f901b4111b1a0000000092030f5468652050696e6b2053616c6d6f6e",
      },
      geometry: {
        type: "Point",
        coordinates: [153.03894719999997, -27.51555119945753],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Thai Gold Singha",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4121",
        city_district: "Tarragindi",
        district: "Greater Brisbane",
        suburb: "Tarragindi",
        street: "Ekibin Road East",
        lon: 153.0390215,
        lat: -27.515572,
        state_code: "QLD",
        formatted:
          "Thai Gold Singha, Ekibin Road East, Tarragindi QLD 4121, Australia",
        address_line1: "Thai Gold Singha",
        address_line2: "Ekibin Road East, Tarragindi QLD 4121, Australia",
        categories: [
          "catering",
          "catering.restaurant",
          "catering.restaurant.thai",
        ],
        details: ["details", "details.catering"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Thai Gold Singha",
            osm_id: 437981621,
            amenity: "restaurant",
            cuisine: "thai",
            osm_type: "n",
            opening_hours: "Mo-Su,PH 17:00-22:00",
          },
        },
        opening_hours: "Mo-Su,PH 17:00-22:00",
        catering: {
          cuisine: "thai",
        },
        distance: 1078,
        place_id:
          "51e74a04aa3f216340594267cc86fc833bc0f00103f901b5111b1a000000009203105468616920476f6c642053696e676861",
      },
      geometry: {
        type: "Point",
        coordinates: [153.03902149999996, -27.515571999457514],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Hungry Jack's",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Ipswich Road",
        lon: 153.0314069,
        lat: -27.5136354,
        state_code: "QLD",
        formatted: "Hungry Jack's, Ipswich Road, Annerley QLD 4103, Australia",
        address_line1: "Hungry Jack's",
        address_line2: "Ipswich Road, Annerley QLD 4103, Australia",
        categories: [
          "building",
          "building.catering",
          "catering",
          "catering.fast_food",
          "catering.fast_food.burger",
        ],
        details: ["details", "details.catering", "details.facilities"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Hungry Jack's",
            brand: "Hungry Jack's",
            osm_id: 9703011690,
            amenity: "fast_food",
            cuisine: "burger",
            building: "yes",
            osm_type: "n",
            takeaway: "yes",
            opening_hours: "PH,Mo-Su 12:00",
            "brand:wikidata": "Q3036373",
          },
        },
        opening_hours: "PH,Mo-Su 12:00",
        brand: "Hungry Jack's",
        brand_details: {
          wikidata: "Q3036373",
        },
        facilities: {
          takeaway: true,
        },
        catering: {
          cuisine: "burger",
        },
        distance: 1090,
        place_id:
          "51cc0b0b4901216340591fbd0a9c7d833bc0f00103f9016a3558420200000092030d48756e677279204a61636b2773",
      },
      geometry: {
        type: "Point",
        coordinates: [153.03140689999998, -27.51363539945771],
      },
    },
    {
      type: "Feature",
      properties: {
        name: "Snag & Brown",
        country: "Australia",
        country_code: "au",
        state: "Queensland",
        postcode: "4103",
        city_district: "Annerley",
        district: "Greater Brisbane",
        suburb: "Annerley",
        street: "Ekibin Road",
        housenumber: "97",
        lon: 153.0365409,
        lat: -27.5133772,
        state_code: "QLD",
        formatted: "Snag & Brown, 97 Ekibin Road, Annerley QLD 4103, Australia",
        address_line1: "Snag & Brown",
        address_line2: "97 Ekibin Road, Annerley QLD 4103, Australia",
        categories: ["catering", "catering.cafe"],
        details: ["details"],
        datasource: {
          sourcename: "openstreetmap",
          attribution: "© OpenStreetMap contributors",
          license: "Open Database License",
          url: "https://www.openstreetmap.org/copyright",
          raw: {
            name: "Snag & Brown",
            osm_id: 1607170074,
            amenity: "cafe",
            osm_type: "n",
            "addr:street": "Ekibin Road",
            "addr:suburb": "Annerley",
            "addr:postcode": 4103,
            opening_hours: "Mo-Su 07:00-15:00",
            "addr:housenumber": 97,
          },
        },
        opening_hours: "Mo-Su 07:00-15:00",
        distance: 1180,
        place_id:
          "51ed4ed2572b21634059dc2e2ab06c833bc0f00103f9011a78cb5f0000000092030c536e616720262042726f776e",
      },
      geometry: {
        type: "Point",
        coordinates: [153.0365409, -27.513377199457736],
      },
    },
  ],
};
